(WIP) try graceful process termination
Forced termination might cause failure of the subsequent tests

```
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu bar for shell: Shell with text {No Coverage Data}
	at org.eclipse.eclemma.ui.ExportImportTest.testImport(ExportImportTest.java:34)
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find menu bar for shell: Shell with text {No Coverage Data}
	at org.eclipse.eclemma.ui.ExportImportTest.testImport(ExportImportTest.java:34)
```